### ISSUE TITLE
inventory_hostname

### ISSUE THREAD

**Issue by Scoi4101** [IBM-Security/isam-ansible-roles#18]
So wanted to discuss a concept:

I am looking to reduce the knowledge our developers have about out environment and am looking to create an alias for the RP instance name so that is all they need to supply to execute playbooks

hosts file would be ~
**test-myapp-0024 ansible_host=localhost da_name=test-myapp-0024**

So this causes an issue in that the start_confg process is hard coded to inventory_hostname.

Just wanted to put this here and see what thoughts people have.

Thanks

**Comment by ram-ibm** [comment]
Why not assign group names to the appliances? You could then use the group names for executing playbooks. For example, you could use a group name called "restricted" to contain all appliances with reverse proxies. Supplying "--limit restricted" will make sure that the playbook runs against just those hosts. You could even code your playbook to target appliances using that info like so:
```
- name: Execute against reverse proxies
  hosts: restricted
  connection: local
  roles:
    - role: set_reverseproxy_conf
      set_reverseproxy_conf_reverseproxy_id: "default"
      set_reverseproxy_conf_entries:
      - stanza_id: "authentication-levels"
        entries:
        - ["level", "unauthenticated"]
        - ["level", "ssl"]
        - ["level", "password"]
```
