### ISSUE TITLE
Make registered variable name configurable in search_mapping_rule

### ISSUE THREAD

**Issue by Ardun21** [IBM-Security/isam-ansible-roles#24]
The search_mapping_rule role currently registers the resulting mapping rule ID in a variable which is always called "search_mapping_rule". This causes issues if you need to lookup multiple mapping rule IDs for a single task (i.e. if you are creating a module chain which uses more than one mapping rule, as we frequently do). I have shown in my local environment that by making the name of the registered variable configurable, it is possible to lookup multiple mapping rules within a single task.

Example of the modification to the search_mapping_rule role:
```
- name: Search for a Mapping Rule
  isam:
    appliance: "{{ inventory_hostname }}"
    username:  "{{ username }}"
    password:  "{{ password }}"
    lmi_port:  "{{ lmi_port }}"
    log:       "{{ log_level }}"
    force:     "{{ force }}"
    action: ibmsecurity.isam.aac.mapping_rules.search
    isamapi:
      name: "{{ search_mapping_rule_name }}"
  when: search_mapping_rule_name is defined
  register: "{{ search_mapping_rule_register }}"
```

Example task from playbook:
```
- name: Add Module Chains
  hosts: all
  connection: local
  roles:
    - role: search_mapping_rule
      search_mapping_rule_name: mapping-rule-1
      search_mapping_rule_register: map1

    - role: search_mapping_rule
      search_mapping_rule_name: mapping-rule-2
      search_mapping_rule_register: map2

    - role: add_module_chain
      module_chain_name: test-chain
      module_chain_template_name: test-chain-template
      module_chain_request_type: "http://docs.oasis-open.org/ws-sx/ws-trust/200512/Issue"
      module_chain_description: "Test"
      module_chain_token_type: "*"
      module_chain_issuer:
        address: "REGEXP: (.*/test-chain)"
      module_chain_applies_to:
        address: "REGEXP: (.*)"
      module_chain_properties:
        self:
          - name: map-01.map.rule.reference.ids
            value:
              - "{{ map1['data'] }}"
          - name: map-02.map.rule.reference.ids
            value:
              - "{{ map2['data'] }}
# OMITTED...
```
If this is acceptable, I will submit a pull request for this update.
