### ISSUE TITLE
update_reverseproxy_conf does not handle '%' in entry value correctly

### ISSUE THREAD

**Issue by mlu-ibm** [IBM-Security/isam-ansible-roles#3]
In the playbook snippet below we try to set the request-log-format to a string that contains non-alphanumerical characters such as '{' '%':

```
- role: update_reverseproxy_conf
      update_reverseproxy_conf_reverseproxy_id: "{{ reverseproxy_instance_name }}"
      update_reverseproxy_conf_entries:
        - stanza_id: "logging"
          entry_id: "request-log-format"
          value_id: "TS:%{%Y-%m-%dT%H:%M:%S}t C:%a I:%A U:%{AZN_CRED_PRINCIPAL_NAME}C AL:%{AUTHENTICATION_LEVEL}C SI:%{tagvalue_session_index}C T:%d M:%m ST:%s B:%B F:%F URL:%U"
```

The error is 

```
template error while templating string: Encountered unknown tag 'Y'.. String: TS:%{%Y-%m-%dT%H:%M:%S}t C:%a I:%A U:%{AZN_CRED_PRINCIPAL_NAME}C AL:%{AUTHENTICATION_LEVEL}C SI:%{tagvalue_session_index}C T:%d M:%m ST:%s B:%B F:%F URL:%U"
```

We have tried different ways to escape the string, none of them seems to work. 

I was able to make it work with '!unsafe' directive when make the API call directly:

```
- name: update logging format
  isam:
      appliance: "{{ ISAM_M1_INTERFACE }}"
      password: "{{ ISAM_admin_pw }}"
      action: ibmsecurity.isam.web.reverse_proxy.configuration.entry.add
      isamapi: 
          reverseproxy_id: "{{reverseproxy_id}}"
          stanza_id: "logging"
          entries: [[ 'request-log-format', !unsafe 'TS:%{%Y-%m-%dT%H:%M:%S}t C:%a I:%A U:%{AZN_CRED_PRINCIPAL_NAME}C AL:%{AUTHENTICATION_LEVEL}C SI:%{tagvalue_session_index}C T:%d M:%m ST:%s B:%B F:%F URL:%U' ]]
```

*Note*: the above API calls entry.add, not entry.update, it takes different input - JSON array entries vs entry_id and value_id

However, we were not able to use the roles to add/update/set the value with these special characters.
